Repository hashicorp/levant, pull requests merged in 2018-07, with the labels that each got.

#202 Add loop template function to allow iteration in templating.
  docs/templates.md
  template/funcs.go
Labels: enhancement

#204 Fix option to create rendered template file
  docs/commands.md
Labels: docs

#205 Fix incorrect templates link in docs README.md
  docs/README.md
Labels: docs

#206 Update Levant for 0.2.0 release.
  CHANGELOG.md
  Dockerfile
  README.md
  version/version.go
Labels: build

#210 Addition of .json as variable file format type.
  README.md
  command/deploy.go
  command/render.go
  docs/templates.md
  helper/files.go
  template/render.go
  template/template.go
Labels: enhancement, template

#211 Enable lint check during tests and fix discovered lint issues.
  GNUmakefile
  buildtime/consts.go
  helper/kvflag.go
  main.go
Labels: bug

#212 Add additional template funcs to allow parsing of types.
  template/funcs.go
Labels: enhancement, template

#214 Add documentation for new parse template functions.
  docs/templates.md
Labels: docs, template

#185 Added -allow-stale option into deploy
  command/deploy.go
  levant/deploy.go
  levant/structs/config.go
Labels: enhancement, pending-feedback

#219 Update Levant for 0.3.0 development effort.
  CHANGELOG.md
  version/version.go
Labels: build

#221 Do not fail a deployment when nodes have been filtered during eval.
  levant/deploy.go
Labels: bug, deployment

#82 fixed failure inspector to report on tasks that are restarting
  levant/failure_inspector.go
Labels: bug
