Repository hashicorp/levant, pull requests merged in 2018-06, with the labels that each got.

#184 Provide better command help for deploy and render commands.
  command/deploy.go
  command/render.go
Labels: docs

#187 Fix broken Docker Hub link in README
  README.md
Labels: docs

#189 Add documentation for scale commands and multiple var file feature
  README.md
  docs/README.md
  docs/commands.md
Labels: docs

#190 Document template funcs and move template docs to docs space.
  README.md
  docs/README.md
  docs/templates.md
Labels: docs

#192 Add Consul clients docs and move client docs to docs folder.
  README.md
  docs/README.md
  docs/clients.md
Labels: docs

#194 Update contribution guide to remove ref to old build script.
  .github/CONTRIBUTING.md
Labels: docs

#196 Add `-ignore-no-changes` flag to deploy CLI command
  command/deploy.go
  levant/deploy.go
  levant/plan.go
  levant/structs/config.go
Labels: enhancement

#198 Run tests with -race flag to detect race conditions.
  GNUmakefile
Labels: build, enhancement
