Repository hashicorp/levant, pull requests merged in 2018-10, with the labels that each got.

#240 Add docs for plan command.
  docs/commands.md
Labels: docs

#241 Prepare Levant for 0.2.3 release.
  CHANGELOG.md
  Dockerfile
  README.md
  version/version.go
Labels: build

#242 Prepare for 0.3.0 development effort.
  CHANGELOG.md
  version/version.go
Labels: build

#245 Move to 0.2.4 bug fix dev version.
  CHANGELOG.md
  version/version.go
Labels: build

#244 Fix NPE - seems like a missing initialization
  scale/scale.go
Labels: bug, deployment

#246 Fix bug where job deploys with count 0 hang.
  levant/deploy.go
Labels: bug, deployment

#247 Prepare Levant for 0.2.4 release.
  CHANGELOG.md
  Dockerfile
  README.md
  version/version.go
Labels: build
