Repository hashicorp/levant, pull requests merged in 2018-04, with the labels that each got.

#138 Add a catchall for unhandled failure cases
  levant/failure_inspector.go
Labels: enhancement

#140 Update Levant for 0.1.0 release.
  README.md
  version/version.go
Labels: enhancement

#142 Prepare for 0.1.1 development effort.
  CHANGELOG.md
  version/version.go
Labels: enhancement

#143 Adding force-batch docs to README
  README.md
Labels: docs

#146 Add link to Gitter room in README.
  README.md
Labels: docs

#148 Remove Go 1.9 from travis tests as this is no longer needed.
  .travis.yml
Labels: enhancement

#144 Refactor makefile to GNUmakefile and use gometalinter.
  .travis.yml
  GNUmakefile
  Makefile
  command/deploy.go
  command/dispatch.go
  command/render.go
Labels: enhancement

#150 Fixed batch job checker
  levant/job_status_checker.go
  levant/job_status_checker_test.go
Labels: bug

#152 Fix deadcode lint issue found in job_status_checker.
  levant/job_status_checker.go
Labels: bug

#155 Break levant/deploy function out to make smaller and cleaner.
  levant/deploy.go
Labels: enhancement
