Repository hashicorp/levant, pull requests merged in 2018-05, with the labels that each got.

#165 Update Dockerfile to pull released artefact.
  Dockerfile
Labels: build, enhancement

#169 Add Dockerfile.build to allow building during development.
  Dockerfile
  Dockerfile.build
Labels: build, enhancement

#170 Fix formatting issue with version summary output.
  .goreleaser.yml
Labels: bug, build

#172 Addition of scale-out and scale-in commands.
  client/nomad.go
  command/deploy.go
  command/scale_in.go
  command/scale_out.go
  commands.go
  levant/deploy.go
  levant/dispatch.go
  levant/structs/config.go
  levant/structs/scaling.go
  scale/scale.go
  scale/scale_test.go
Labels: core-design, enhancement

#175 Addition of template functions allow Consul and Time lookups.
  client/consul.go
  command/deploy.go
  command/deploy_test.go
  command/render.go
  template/funcs.go
  template/render.go
  template/render_test.go
  template/template.go
Labels: core-design, enhancement

#178 typo and message fixup
  command/scale_in.go
Labels: bug
