Repository hashicorp/levant, pull requests merged in 2019-11, with the labels that each got.

#314 Prepare for 0.2.9 development effort.
  CHANGELOG.md
  version/version.go
Labels: build

#311 Installation tip for macOS
  README.md
Labels: docs, enhancement

#303 levant/plan: Use info level logs when no changes are detected
  levant/plan.go
Labels: bug
