Repository hashicorp/levant, pull requests merged in 2019-02, with the labels that each got.

#264 Fix miss behavior when flag 'ignore-no-changes' was set.
  command/deploy.go
  command/plan.go
  levant/plan.go
Labels: bug, deployment

#269 Update goreleaser install on travis from source rather than go get
  .travis.yml
  GNUmakefile
Labels: bug, build

#268 Fix deploy loop bug when evaluation didn't include a deployment ID.
  Gopkg.lock
  levant/deploy.go
  vendor/github.com/pkg/errors/.gitignore
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/bench_test.go
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/errors_test.go
  vendor/github.com/pkg/errors/example_test.go
  vendor/github.com/pkg/errors/format_test.go
  vendor/github.com/pkg/errors/stack.go
  vendor/github.com/pkg/errors/stack_test.go
Labels: bug, deployment

#270 Release version 0.2.6 of Levant.
  CHANGELOG.md
  Dockerfile
  README.md
  version/version.go
Labels: build, enhancement

#271 Ensure travis Levant clone is clean for releases.
  .travis.yml
Labels: bug, build
