Repository hashicorp/levant, pull requests merged in 2021-11, with the labels that each got.

#433 docs: clarify source for official release binaries
  README.md
Labels: theme/docs

#425 Update example for `replace` function.
  docs/templates.md
Labels: type/bug, theme/docs

#435 deps: update Nomad API.
  go.mod
Labels: type/enhancement, stage/accepted, theme/dependency
